import type { ContentItem } from "./types";
import { generateId } from "./utils";

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: generateId(),
    contentId: "10001",
    name: "Hero Serum Launch Video",
    mediaType: "video",
    channel: "Official",
    platforms: ["facebook", "instagram", "tiktok"],
    details: "วิดีโอเปิดตัว Hero Serum สไตล์ lifestyle herbal",
    location: ["Studio A"],
    scheduledDate: "2026-06-15",
    scheduledTime: "10:00",
    endTime: "12:00",
    team: [
      { id: "1", participant: "Laura Power", responsibility: "Presenter" },
      { id: "2", participant: "วิชัย สร้างสรรค์", responsibility: "Camera" },
    ],
    productsNeeded: ["Hero Serum"],
    itemsToPrepare: "Backdrop สีเขียว, Props สมุนไพร",
    attachments: [],
    script: [
      {
        id: "s1",
        startTime: "00:00",
        endTime: "00:15",
        action: "Open with product shot",
        dialogue: "สวัสดีค่ะ วันนี้มาแนะนำ Hero Serum",
        notes: "Close-up macro",
      },
    ],
    ideaCreator: "Laura Power",
    photographer: "พิมพ์ใจ ถ่ายทำ",
    editor: "กนก ตัดต่อ",
    status: "approved",
    category: "Hero Video",
    tags: ["Hero Product"],
    createdAt: "2026-06-10T08:00:00Z",
  },
  {
    id: generateId(),
    contentId: "10002",
    name: "Farm Fresh Behind the Scenes",
    mediaType: "video",
    channel: "วังน้ำเขียวฟาร์ม",
    platforms: ["facebook", "tiktok", "line"],
    details: "Behind the scenes การเก็บเกี่ยวสมุนไพรที่ฟาร์ม",
    location: ["Farm Location"],
    scheduledDate: "2026-06-17",
    scheduledTime: "09:00",
    endTime: "11:00",
    team: [
      { id: "1", participant: "มานี มีสุข", responsibility: "Presenter" },
    ],
    productsNeeded: ["Herbal Tea Set"],
    itemsToPrepare: "Outdoor mic, Drone",
    attachments: [],
    script: [],
    ideaCreator: "มานี มีสุข",
    photographer: "พิมพ์ใจ ถ่ายทำ",
    editor: "กนก ตัดต่อ",
    status: "pending",
    category: "Behind the Scenes",
    tags: ["Farm"],
    createdAt: "2026-06-12T10:00:00Z",
  },
  {
    id: generateId(),
    contentId: "10003",
    name: "Gift Set Teaser",
    mediaType: "image",
    channel: "ของชำร่วย",
    platforms: ["instagram", "lemon8"],
    details: "ภาพ Teaser ชุดของขวัญสมุนไพร",
    location: ["Studio A"],
    scheduledDate: "2026-06-18",
    scheduledTime: "14:00",
    endTime: "15:00",
    team: [],
    productsNeeded: ["Gift Set"],
    itemsToPrepare: "Ribbon, Gift box props",
    attachments: [],
    script: [],
    ideaCreator: "Laura Power",
    photographer: "พิมพ์ใจ ถ่ายทำ",
    editor: "กนก ตัดต่อ",
    status: "pending",
    category: "Recap / Teaser",
    tags: ["Gift"],
    createdAt: "2026-06-13T14:00:00Z",
  },
  {
    id: generateId(),
    contentId: "10004",
    name: "Wellness Bundle Review",
    mediaType: "video",
    channel: "สายพี่ป๋อง",
    platforms: ["tiktok", "youtube"],
    details: "รีวิว Wellness Bundle แบบ casual",
    location: ["Kitchen Set"],
    scheduledDate: "2026-06-20",
    scheduledTime: "16:00",
    endTime: "18:00",
    team: [
      { id: "1", participant: "สมชาย ใจดี", responsibility: "Presenter" },
    ],
    productsNeeded: ["Wellness Bundle"],
    itemsToPrepare: "",
    attachments: [],
    script: [],
    ideaCreator: "สมชาย ใจดี",
    photographer: "วิชัย สร้างสรรค์",
    editor: "กนก ตัดต่อ",
    status: "approved",
    category: "Product Review",
    tags: ["Wellness"],
    createdAt: "2026-06-14T09:00:00Z",
  },
  {
    id: generateId(),
    contentId: "10005",
    name: "Herbal Lifestyle Post",
    mediaType: "image",
    channel: "ลูกสาว",
    platforms: ["instagram", "facebook"],
    details: "โพสต์ lifestyle สมุนไพรในชีวิตประจำวัน",
    location: ["Office"],
    scheduledDate: "2026-06-22",
    scheduledTime: "11:00",
    endTime: "12:00",
    team: [],
    productsNeeded: ["Herbal Tea Set"],
    itemsToPrepare: "Cup set, Natural light",
    attachments: [],
    script: [],
    ideaCreator: "Laura Power",
    photographer: "พิมพ์ใจ ถ่ายทำ",
    editor: "กนก ตัดต่อ",
    status: "scheduled",
    category: "Lifestyle",
    tags: ["Daily"],
    createdAt: "2026-06-15T11:00:00Z",
  },
];
