import type { ContentItem } from "./types";
import { generateId } from "./utils";

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: generateId(),
    contentId: "NKT0001",
    name: "Hero Serum Launch Video",
    mediaType: "video",
    channel: "nook__th",
    platforms: ["instagram"],
    details: "วิดีโอเปิดตัว Hero Serum สไตล์ lifestyle herbal",
    location: ["Studio A"],
    scheduledDate: "2026-06-15",
    scheduledTime: "10:00",
    endTime: "12:00",
    ideaFinishedDate: "2026-06-10",
    shootDate: "2026-06-12",
    editFinishedDate: "2026-06-14",
    team: [
      { id: "1", participant: "Laura Power", responsibility: "Presenter" },
      { id: "2", participant: "วิชัย สร้างสรรค์", responsibility: "Camera" },
    ],
    productsNeeded: ["Hero Serum"],
    itemsToPrepare: "Backdrop สีเขียว, Props สมุนไพร",
    filmingEquipment: ["Camera", "Lighting"],
    attachments: [],
    script: [
      {
        id: "s1",
        startTime: "00:00",
        endTime: "00:15",
        action: "Open with product shot",
        dialogue: "สวัสดีค่ะ วันนี้มาแนะนำ Hero Serum",
        notes: "Close-up macro",
      },
    ],
    ideaCreator: "Laura Power",
    photographer: "พิมพ์ใจ ถ่ายทำ",
    editor: "กนก ตัดต่อ",
    status: "approved",
    category: "Hero Video",
    tags: ["Hero Product"],
    createdAt: "2026-06-10T08:00:00Z",
  },
  {
    id: generateId(),
    contentId: "NKD0001",
    name: "Farm Fresh Behind the Scenes",
    mediaType: "video",
    channel: "nook_down",
    platforms: ["tiktok"],
    details: "Behind the scenes การเก็บเกี่ยวสมุนไพรที่ฟาร์ม",
    location: ["Farm Location"],
    scheduledDate: "2026-06-17",
    scheduledTime: "09:00",
    endTime: "11:00",
    ideaFinishedDate: "",
    shootDate: "2026-06-16",
    editFinishedDate: "",
    team: [
      { id: "1", participant: "มานี มีสุข", responsibility: "Presenter" },
    ],
    productsNeeded: ["Herbal Tea Set"],
    itemsToPrepare: "Outdoor setup",
    filmingEquipment: ["Microphone", "Drone"],
    attachments: [],
    script: [],
    ideaCreator: "มานี มีสุข",
    photographer: "พิมพ์ใจ ถ่ายทำ",
    editor: "กนก ตัดต่อ",
    status: "pending",
    category: "Behind the Scenes",
    tags: ["Farm"],
    createdAt: "2026-06-12T10:00:00Z",
  },
  {
    id: generateId(),
    contentId: "ICP0001",
    name: "Gift Set Teaser",
    mediaType: "image",
    channel: "idea_content_post",
    platforms: ["instagram"],
    details: "ภาพ Teaser ชุดของขวัญสมุนไพร",
    location: ["Studio A"],
    scheduledDate: "2026-06-18",
    scheduledTime: "14:00",
    endTime: "15:00",
    ideaFinishedDate: "2026-06-13",
    shootDate: "",
    editFinishedDate: "",
    team: [],
    productsNeeded: ["Gift Set"],
    itemsToPrepare: "Ribbon, Gift box props",
    filmingEquipment: [],
    attachments: [],
    script: [],
    ideaCreator: "Laura Power",
    photographer: "พิมพ์ใจ ถ่ายทำ",
    editor: "กนก ตัดต่อ",
    status: "pending",
    category: "Recap / Teaser",
    tags: ["Gift"],
    createdAt: "2026-06-13T14:00:00Z",
  },
];
